server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: mini-door-dash-backend
  
  # Disable database for health check only
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    root: INFO
    com.minidoordash: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 