server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: mini-door-dash-backend

  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://db.fbqinbkfgckofqokgevu.supabase.co:5432/postgres?sslmode=require}
    username: ${SUPABASE_DB_USER:postgres}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  security:
    user:
      name: admin
      password: admin

supabase:
  url: ${SUPABASE_URL:https://fbqinbkfgckofqokgevu.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY}
  service-key: ${SUPABASE_SERVICE_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.minidoordash: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 